version: '2'
services:
  web:
    image: nginx:1.15.0
    volumes:
      - ./:/var/www/html
    ports:
      - "8882:80"
    links:
      - app

  app:
      build:
        context: ./
        dockerfile: app.dockerfile
      working_dir: /var/www/html
      volumes:
        - ./:/var/www/html
      environment:
        - "DB_PORT=3306"
        - "DB_HOST=database"


  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root